### PR TITLE
ENH: Build Python package against ITK 5.0.0.post1

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by T4mmi — APPROVED** [review]

**Comment by T4mmi** [comment]
Hi @thewtex, I'm trying to DL the wheels in order to produce the correct "MedialThickness" test image outpout and validate the tests .... but:
```{"$id":"1","innerException":null,"message":"TF400813: The user 'Windows Live ID\\thomas.p.janvier@gmail.com' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}```
How to get access to the build artifacts on azure pipeline ?

**Comment by thewtex** [comment]
@T4mmi I sent an invite to thomas.p.janvier@gmail.com for the Azure account. After logging in, can you access the build artifacts?

**Comment by T4mmi** [comment]
Yeah thanks, I finally managed to build my own fork on azure using a separate pipeline ;)
But hadn't time to test it yet, probably tomorrow

**Comment by thewtex** [comment]
Cool -- going forward, in general, the best practice will be to have a separate Azure Pipeline account per repository. We can disable the ITKModules Azure build on this repository if you have another set up.

**Pull request merged**
