### PR TITLE
ENH: Transition `README`to reSTructuredText.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transition `README` to reSTructuredText to conform to the
`ITKModuleTemplate` guidelines.

Take advantage of the commit to fix some typos.

Remove trailing whitespaces.

### CODE REVIEW

**Review by T4mmi — COMMENTED** [review]
I don't know if RST is mandatory.. (I'm not a big fan to be honest)
But if you change it then you have to change the README filename in https://github.com/InsightSoftwareConsortium/ITKThickness3D/blob/master/itk-module.cmake#L4

**Comment by jhlegarreta** [comment]
@T4mmi thanks for the review ! Yes, I missed that.

The `ITKModuleTemplate` does implicitly recommend using reSTructuredText. I guess the Cookiecutter module used to generate the files created an `.rst`. It is more about consistency. There are many subtleties throughout the toolkit that we may disagree on, but keeping consistency is an important aspect beyond our own choices !

**Comment by T4mmi** [comment]
Actually coockiecutter did create a reStructureText README, I did convert it to markdown 😐
But you're right about consistency !

**Comment by jhlegarreta** [comment]
Thanks for understanding Thomas, and sorry if you took the time to convert it to Markdown.

**Comment by T4mmi** [comment]
No problem, I'm learning 😉

**Pull request merged**
