### PR TITLE
STYLE: Conform to ITK coding style guidelines.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Conform to ITK coding style guidelines:
- Use the `this` keyword to call to member functions.
- Document the methods when being declared.
- Remove reimplemented methods' documentation.
- Use braces for flow control loops, even if they consist of a single
  line.
- Use `unsigned int` types for indexing.
- Make flow control loop variables have a local scope.
- Use pre-increment in recursive control loops.
- Use the appropriate indentation.
- Start comments with capitals.
- Make `PrintSelf` be the last method of the implementation body.
- Remove uninformative `PrintSelf` `std::cout` message.
- Remove `itkDebugMacro` messages.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
In line with #10 , increase consistency across the toolkit code and improve readability.

**Comment by jhlegarreta** [comment]
White spaces between brackets and arguments in control flow statement arguments and methods are also recommended by the ITK style guidelines, but this has been subject to changes as per the ITK KW Style if I'm not mistaken.

**Comment by thewtex** [comment]
CI caught build errors.

**Comment by T4mmi** [comment]
I'll look into it on Monday

**Comment by jhlegarreta** [comment]
CI failures were due to oversights I made. 8f3a1a9 should be OK. Also resolved the conflicts and rebased on master.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
