### PR TITLE
Updates for ITKv5.2 code cleanups ... ROUND1

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Review by jhlegarreta — COMMENTED** [review]
**Thanks** for the monumental effort of updating all remotes Hans.

Not sure about the compilation errors and warnings reported by CI. I could not find the builds in CDash and Azure's output does not seem to show the lines where they happened.

As for the tests, no test was actually run apart from the Doxygen documentation one:
```
	  1 - Thickness3DKWStyleTest (Not Run)
	  3 - itkBinaryThinningImageFilter3DTest (Not Run)
	  4 - itkMedialThicknessImageFilter3DTest (Not Run)
```

Not sure why the test driver is not being found. The `master` shows a passing Azure CI badge, but when clicking on the badge, no build can actually be found.

Not sure if this is related, but may be the `ITKGitTag` needs to be updated to in the Azure CI pipelines file?

**Comment by jhlegarreta** [comment]
The reported KWStyle issue may be due to the fact the difference in the copyright holder in the header between these files and the tested ITK. Updating the `ITKGitTag` in the Azure pipelines YAML file should fix the issue I guess.

**Comment by hjmjohnson** [comment]
> The reported KWStyle issue may be due to the fact the difference in the copyright holder in the header between these files and the tested ITK. Updating the `ITKGitTag` in the Azure pipelines YAML file should fix the issue I guess.

`Could not find executable /home/vsts/work/1/build/KWStyle-build/KWStyle`

**Comment by hjmjohnson** [comment]
Incremental improvement.  Other issues to be addressed in the future

**Pull request merged**
