### PR TITLE
ENH: Remove unused CI config files

### PR DESCRIPTION
**Pull request by jhlegarreta**
Remove unused CI config files.

Appveyor, Travis, and Circle were superseded by Azure Pipelines CI in
29dd1d0.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex Shouldn't the `azure-pipelines.yml` be placed in the root instead of the `test` folder?

**Comment by jhlegarreta** [comment]
@T4mmi would you disable the Appveyor, Circle and Travis builds?

**Comment by thewtex** [comment]
> @thewtex Shouldn't the `azure-pipelines.yml` be placed in the root instead of the `test` folder?

I think we should place the configuration in the *test* folder to avoid top level clutter. Some existing modules still need to be updated for this.

> @T4mmi would you disable the Appveyor, Circle and Travis builds?

:+1: Done

**Review by thewtex — APPROVED** [review]

**Comment by T4mmi** [comment]
@thewtex this means that CI build  file should be placed in test folder for every ITK modules ?
(or just while the transition from Travis/Circle/appveyor to Azure pipes ?)

**Comment by thewtex** [comment]
Yes, we should put the CI build file in the *test* folder for all ITK modules. Azure Pipelines make it optional where the configuration file is located, but that flexibility is not available in other services.

**Pull request merged**
